package com.example.lexora.user.enums;

/**
 *
 * @author Miguel
 */
public enum Specialite {

    DROIT_CIVIL,
    DROIT_DE_LA_FAMILLE,
    DROIT_FONCIER_ET_IMMOBILIER,
    DROIT_DU_TRAVAIL,
    DROIT_PENAL,
    DROIT_DES_AFFAIRES,
    DROIT_OHADA,
    DROIT_BANCAIRE_ET_FINANCIER,
    DROIT_DES_ASSURANCES,
    DROIT_FISCAL_ET_DOUANIER,
    DROIT_ADMINISTRATIF,
    DROIT_CONSTITUTIONNEL,
    DROITS_HUMAINS,
    DROIT_INTERNATIONAL,
    PROPRIETE_INTELLECTUELLE,
    DROIT_DU_NUMERIQUE,
    DROIT_DE_L_ENVIRONNEMENT,
    DROIT_DES_RESSOURCES_NATURELLES,
    DROIT_DES_TRANSPORTS,
    DROIT_DE_LA_SANTE,
    AUTRE,
    NON_DETERMINE
}
